name: build and publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Test
        run: dotnet test --no-build --verbosity normal -c Release
      - name: Package
        run: dotnet pack -c Release --no-build -output .
      - name: Nuget package publish
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        run: dotnet nuget push "./*.nupkg" --api-key $NUGET_KEY
      - name: Nuget symbol package publish
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        run: dotnet nuget push "./*.snupkg" --api-key $NUGET_KEY
